name: DrTransformer in a miniconda setup 

on: [push]

jobs:
  trafo-tests:
    name: trafo-env (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: trafo
          python-version: ${{ matrix.python-version }}
          # The order of channes is in reverse! *Very important*
          channels: conda-forge,bioconda,defaults
          channel-priority: strict
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Install viennarna
        run: |
          conda install "viennarna>=2.5.1"
      - name: Install devtools
        run: |
          conda install flake8 pytest pytest-cov
      - name: Install package 
        run: |
          python -m pip install .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest --cov-report term --cov=drtransformer/
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: ${{ success() }}
